services:
  - type: web
    name: titanic-fastapi
    runtime: python  # ✅ Dùng 'runtime', bỏ 'env'
    plan: free
    region: singapore
    branch: main
    buildCommand: ""  # ✅ Nếu không cần build gì thêm
    startCommand: uvicorn main:app --host=0.0.0.0 --port=8000
