services:
  - type: web
    name: titanic-fastapi
    env: docker
    plan: free
    dockerCommand: "docker build -t titanic-fastapi ."
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PORT
        value: 10000